"""relationship delete cascada

Revision ID: 1228fe57fbbc
Revises: 6b3e0d2a4cf9
Create Date: 2024-07-18 15:56:25.075746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1228fe57fbbc'
down_revision: Union[str, None] = '6b3e0d2a4cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_interests_ibfk_1', 'user_interests', type_='foreignkey')
    op.drop_constraint('user_interests_ibfk_2', 'user_interests', type_='foreignkey')
    op.create_foreign_key(None, 'user_interests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_interests', 'interests', ['interest_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'user_interests', type_='foreignkey')
    op.drop_constraint(None, 'user_interests', type_='foreignkey')
    op.create_foreign_key('user_interests_ibfk_2', 'user_interests', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_interests_ibfk_1', 'user_interests', 'interests', ['interest_id'], ['id'])
    # ### end Alembic commands ###
